
using System.Collections.Generic;

public class EntityCategory : Category<EntityEntry>
{
    public EntityCategory()
    {
        AddRange(new List<EntityEntry>()
        {
            new("Entity01_001", "徐福",               modelName: "徐福"),
            new("Entity01_002", "子非鱼",             modelName: "子非鱼"),
            new("Entity01_003", "子非燕",             modelName: "子非燕"),
            new("Entity01_004", "彼此卿",             modelName: "彼此卿"),
            new("Entity01_005", "风雨晴",             modelName: "风雨晴"),
            new("Entity0001", "鶸",                   modelName: "噬金甲"),
            new("Entity0002", "噬金甲",               modelName: "噬金甲"),
            new("Entity0003", "墨蛟",                 modelName: "墨蛟"),
            new("Entity0004", "渊虾",                 modelName: "渊虾"),
            new("Entity0005", "九尾狐",               modelName: "九尾狐"),
            new("Entity0006", "推山兽",               modelName: "推山兽"),
            new("Entity0007", "白泽",                 modelName: "白泽"),
            new("Entity0008", "鲲",                   modelName: "鲲"),
            new("Entity0009", "毕方",                 modelName: "毕方"),
            new("Entity0010", "火蟾",                 modelName: "火蟾"),
            new("Entity0011", "麒麟",                 modelName: "麒麟"),
            new("Entity0012", "凌霄大圣",              modelName: "凌霄大圣"),
            new("Entity0013", "龟仙人",                modelName: "龟仙人"),
            new("Entity0014", "鹿仙人",                modelName: "鹿仙人"),
            new("Entity0015", "鹤仙人",                modelName: "鹤仙人"),
            new("Entity0016", "土行大圣",              modelName: "土行大圣"),
            new("Entity0017", "置入教学怪物",           modelName: "噬金甲"),
            new("Entity0018", "灵气教学怪物",           modelName: "噬金甲"),
            new("Entity0019", "合成教学怪物",           modelName: "噬金甲"),
            new("Entity0020", "战败教学怪物",           modelName: "噬金甲"),
            new("Entity0021", "教学怪物1",             modelName: "噬金甲"),
            new("Entity0022", "教学怪物2",             modelName: "噬金甲"),
            new("Entity0023", "教学怪物3",             modelName: "噬金甲"),
            new("Entity0024", "教学怪物4",             modelName: "风雨晴"),
            new("Entity0025", "教学怪物5",             modelName: "风雨晴"),
            new("Entity0026", "教学怪物6",             modelName: "噬金甲"),
            new("Entity0027", "教学怪物7",             modelName: "噬金甲"),
            new("Entity0028", "教学怪物8",             modelName: "噬金甲"),
            new("Entity0029", "教学怪物9",             modelName: "噬金甲"),
            new("Entity0030", "教学怪物10",            modelName: "风雨晴"),
            new("Entity0031", "教学怪物11",            modelName: "风雨晴"),
            new("Entity0032", "教学怪物12",            modelName: "渊虾"),
            new("Entity0033", "教学怪物13",            modelName: "渊虾"),
            new("Entity0034", "玩家手牌1",             modelName: "风雨晴"),
            new("Entity0035", "玩家手牌2",             modelName: "风雨晴"),
            new("Entity0036", "玩家手牌3",             modelName: "风雨晴"),
            new("Entity0037", "玩家手牌4",             modelName: "风雨晴"),
            new("Entity0038", "玩家手牌5",             modelName: "风雨晴"),
            new("Entity0039", "玩家手牌6",             modelName: "风雨晴"),
            new("Entity0040", "玩家手牌7",             modelName: "风雨晴"),
            new("Entity0041", "玩家手牌8",             modelName: "风雨晴"),
            new("Entity0042", "玩家手牌9",             modelName: "风雨晴"),
            new("Entity0043", "玩家手牌10",            modelName: "风雨晴"),
            new("Entity0044", "玩家手牌11",            modelName: "风雨晴"),
            new("Entity0045", "玩家手牌12",            modelName: "风雨晴"),
            new("Entity0046", "多段HomeA",            modelName: "风雨晴"),
            new("Entity0047", "多段AwayA",            modelName: "风雨晴"),
            new("Entity0048", "多段HomeB",            modelName: "风雨晴"),
            new("Entity0049", "多段AwayB",            modelName: "风雨晴"),
            new("Entity0050", "多段HomeC",            modelName: "风雨晴"),
            new("Entity0051", "多段AwayC",            modelName: "风雨晴"),
            new("Entity0052", "多段HomeD",            modelName: "风雨晴"),
            new("Entity0053", "多段AwayD",            modelName: "风雨晴"),
            new("Entity0054", "排局1",                modelName: "噬金甲"),
            new("Entity0055", "排局2",                modelName: "噬金甲"),
            new("Entity0056", "排局3",                modelName: "噬金甲"),
        });
    }

    public EntityEntry Default() => FromName("鶸");
}
