
using System.Collections.Generic;

public class SpriteCategory : Category<SpriteEntry>
{
    public SpriteCategory()
    {
        AddRange(new List<SpriteEntry>()
        {
            // BuffIcons
            new("不存在的状态", "Images/BuffIcons/不存在"),
            new("缺失状态插画", "Images/BuffIcons/无图标"),
            new("二动", "Images/BuffIcons/二动"),
            new("力量", "Images/BuffIcons/力量"),
            new("吸血", "Images/BuffIcons/吸血"),
            new("暴击", "Images/BuffIcons/暴击"),
            new("格挡", "Images/BuffIcons/格挡"),
            new("永久暴击", "Images/BuffIcons/永久暴击"),
            new("灼烧", "Images/BuffIcons/灼烧"),
            new("穿透", "Images/BuffIcons/穿透"),
            new("锋锐", "Images/BuffIcons/锋锐"),
            new("闪避", "Images/BuffIcons/闪避"),
            
            // NodeIcons
            new("奇遇", "Images/NodeIcons/Adventure"),
            new("战斗", "Images/NodeIcons/Battle"),
            new("Boss", "Images/NodeIcons/Boss"),
            new("事件", "Images/NodeIcons/Event"),
            new("金钱", "Images/NodeIcons/JinQian"),
            new("人参", "Images/NodeIcons/RenShen"),
            new("人参果", "Images/NodeIcons/RenShenGuo"),
            new("商店", "Images/NodeIcons/Shop"),
            new("算卦", "Images/NodeIcons/SuanGua"),
            new("温泉", "Images/NodeIcons/WenQuan"),
            new("悟道", "Images/NodeIcons/WuDao"),
            new("修炼", "Images/NodeIcons/XiuLian"),
            new("以物易物", "Images/NodeIcons/YiWuYiWu"),

            // 演出用
            new("同境界合成教学1", "Images/Cutscenes/同境界合成教学1"),
            new("同境界合成教学2", "Images/Cutscenes/同境界合成教学2"),
            new("同境界合成教学3", "Images/Cutscenes/同境界合成教学3"),
            new("命元教学1", "Images/Cutscenes/命元教学1"),
            new("命元教学2", "Images/Cutscenes/命元教学2"),
            new("命元教学3", "Images/Cutscenes/命元教学3"),
            new("战斗教学1", "Images/Cutscenes/战斗教学1"),
            new("战斗教学2", "Images/Cutscenes/战斗教学2"),
            new("战斗教学3", "Images/Cutscenes/战斗教学3"),
            new("漫画1", "Images/Cutscenes/漫画1"),
            new("漫画2", "Images/Cutscenes/漫画2"),
            new("漫画3", "Images/Cutscenes/漫画3"),
            new("漫画4", "Images/Cutscenes/漫画4"),
            new("漫画5", "Images/Cutscenes/漫画5"),

            // 卡牌
            new("缺失卡面插画", "Images/CardIllustrations/Default"),
            new("聚气术", "Images/Cards/聚气术"),
            new("冲撞", "Images/Cards/冲撞"),
            
            new("摇曳", "Images/Cards/摇曳"),
            new("金刃", "Images/Cards/金刃"),
            new("寻猎", "Images/Cards/利剑"),
            new("刺穴", "Images/Cards/刺穴"),
            new("金鳞", "Images/Cards/铁布衫"),
            new("流云", "Images/Cards/流云"),
            new("天地同寿", "Images/Cards/满招损"),
            new("诸行无常", "Images/Cards/诸行无常"),
            new("凛冽", "Images/Cards/凛冽"),
            new("袖里乾坤", "Images/Cards/灵气转格挡"),
            new("齐物论", "Images/Cards/森罗万象"),
            new("无妄", "Images/Cards/无妄"),
            new("化神金", "Images/Cards/摩利支天咒"),
            new("人间无戈", "Images/Cards/千里神行符"),
            new("暴雨梨花针", "Images/Cards/无极剑阵"),
            new("吐纳", "Images/Cards/吐纳"),
            new("恋花", "Images/Cards/恋花"),
            new("冰肌", "Images/Cards/冰弹"),
            new("不动明王咒", "Images/Cards/不动明王咒"),
            new("止水", "Images/Cards/一虚一实"),
            new("一闪", "Images/Cards/腾跃"),
            new("瑞雪", "Images/Cards/冰雨"),
            new("抱朴", "Images/Cards/抱元守一"),
            new("腾浪", "Images/Cards/激流"),
            new("气吞山河", "Images/Cards/气吞山河"),
            new("幻月狂乱", "Images/Cards/幻月狂乱"),
            new("敛息", "Images/Cards/软剑"),
            new("奔腾", "Images/Cards/奔腾"),
            new("摩诃钵特摩", "Images/Cards/透骨严寒"),
            new("一梦如是", "Images/Cards/一梦如是"),
            new("若竹", "Images/Cards/若竹"),
            new("小松", "Images/Cards/突刺"),
            new("缭乱", "Images/Cards/花舞"),
            new("回春", "Images/Cards/早春"),
            new("断筋", "Images/Cards/千年笋"),
            new("潜龙在渊", "Images/Cards/潜龙在渊"),
            new("落英", "Images/Cards/清泉"),
            new("盛开", "Images/Cards/盛开"),
            new("见龙在田", "Images/Cards/见龙在田"),
            new("鹤回翔", "Images/Cards/鹤回翔"),
            new("心斋", "Images/Cards/心斋"),
            new("飞龙在天", "Images/Cards/飞龙在天"),
            new("刷新", "Images/Cards/二重"),
            new("通透世界", "Images/Cards/汇聚"),
            new("亢龙有悔", "Images/Cards/亢龙有悔"),
            new("舍生", "Images/Cards/凝神"),
            new("轰天", "Images/Cards/聚火"),
            new("云袖", "Images/Cards/云袖"),
            new("正念", "Images/Cards/敛息"),
            new("三味", "Images/Cards/贪狼"),
            new("九射", "Images/Cards/凤来朝"),
            new("登宝塔", "Images/Cards/玄冰刺"),
            new("天衣无缝", "Images/Cards/天衣无缝"),
            new("剑王行", "Images/Cards/收刀"),
            new("观众生", "Images/Cards/廉贞"),
            new("淬体", "Images/Cards/淬体"),
            new("化劲", "Images/Cards/化劲"),
            new("净天地", "Images/Cards/净天地"),
            new("凤凰涅槃", "Images/Cards/凤凰涅槃"),
            new("天女散花", "Images/Cards/天女散花"),
            new("马步", "Images/Cards/勤能补拙"),
            new("寸劲", "Images/Cards/承"),
            new("落石", "Images/Cards/落石"),
            new("鹤翼", "Images/Cards/乘风"),
            new("玉骨", "Images/Cards/铁骨"),
            new("一力降十会", "Images/Cards/一力降十会"),
            new("逆脉", "Images/Cards/燃命"),
            new("两仪", "Images/Cards/少阴"),
            new("点穴", "Images/Cards/回响"),
            new("龟息", "Images/Cards/玄武吐息法"),
            new("天人合一", "Images/Cards/天人合一"),
            new("龙象", "Images/Cards/武曲"),
            new("化神土", "Images/Cards/流沙"),
            new("那由他", "Images/Cards/业火"),
            new("迦楼罗", "Images/Cards/破军"),
            
            new("燃灯留烬", "Images/Cards/燃灯留烬"),
            new("一切皆苦", "Images/Cards/一切皆苦"),
            new("化焰", "Images/Cards/化焰"),
            new("合", "Images/Cards/合"),
            new("土墙", "Images/Cards/土墙"),
            new("地龙", "Images/Cards/地龙"),
            new("常夏", "Images/Cards/常夏"),
            new("归意", "Images/Cards/归意"),
            new("木剑", "Images/Cards/木剑"),
            new("初桃", "Images/Cards/初桃"),
            new("秋水", "Images/Cards/秋水"),
            new("灵动", "Images/Cards/灵动"),
            new("观棋烂柯", "Images/Cards/观棋烂柯"),
            new("盘旋", "Images/Cards/盘旋"),
        });
    }

    public SpriteEntry MissingSkillIllustration() => this["缺失卡面插画"];
    public SpriteEntry ErrorBuffIcon() => this["不存在的状态"];
    public SpriteEntry MissingBuffIcon() => this["缺失状态插画"];
}
