
using System.Collections.Generic;

public class SpriteCategory : Category<SpriteEntry>
{
    public SpriteCategory()
    {
        AddRange(new List<SpriteEntry>()
        {
            new("缺失卡面插画", "Images/MissingSprite"),
            
            // BuffIcons
            new("Buff不存在", "Images/BuffIcons/不存在"),
            new("Buff缺失插画", "Images/BuffIcons/缺失插画"),
            
            new("Buff抱朴", "Images/BuffIcons/抱朴"),
            new("Buff暴击", "Images/BuffIcons/暴击"),
            new("Buff不堪一击", "Images/BuffIcons/不堪一击"),
            new("Buff缠绕", "Images/BuffIcons/缠绕"),
            new("Buff穿透", "Images/BuffIcons/穿透"),
            new("Buff多重", "Images/BuffIcons/多重"),
            new("Buff二动", "Images/BuffIcons/二动"),
            new("Buff锋锐", "Images/BuffIcons/锋锐"),
            new("Buff腐朽", "Images/BuffIcons/腐朽"),
            new("Buff格挡", "Images/BuffIcons/格挡"),
            new("Buff观众生", "Images/BuffIcons/观众生"),
            new("Buff架势", "Images/BuffIcons/架势"),
            new("Buff坚毅", "Images/BuffIcons/坚毅"),
            new("Buff禁止二动", "Images/BuffIcons/禁止二动"),
            new("Buff禁止行动", "Images/BuffIcons/禁止行动"),
            new("Buff禁止治疗", "Images/BuffIcons/禁止治疗"),
            new("Buff力量", "Images/BuffIcons/力量"),
            new("Buff敛息", "Images/BuffIcons/敛息"),
            new("Buff灵气", "Images/BuffIcons/灵气"),
            new("Buff灵气返还", "Images/BuffIcons/灵气返还"),
            new("Buff轮暴击", "Images/BuffIcons/轮暴击"),
            new("Buff轮穿透", "Images/BuffIcons/轮穿透"),
            new("Buff轮吸血", "Images/BuffIcons/轮吸血"),
            new("Buff免费", "Images/BuffIcons/免费"),
            new("Buff内伤", "Images/BuffIcons/内伤"),
            new("Buff疲劳", "Images/BuffIcons/疲劳"),
            new("Buff清心", "Images/BuffIcons/清心"),
            new("Buff软弱", "Images/BuffIcons/软弱"),
            new("Buff闪避", "Images/BuffIcons/闪避"),
            new("Buff太虚", "Images/BuffIcons/太虚"),
            new("Buff跳行动", "Images/BuffIcons/跳行动"),
            new("Buff跳卡牌", "Images/BuffIcons/跳卡牌"),
            new("Buff跳走步", "Images/BuffIcons/跳走步"),
            new("Buff禁止攻击", "Images/BuffIcons/禁止攻击"),
            new("Buff禁止聚灵", "Images/BuffIcons/禁止聚灵"),
            new("Buff吸血", "Images/BuffIcons/吸血"),
            new("Buff心斋", "Images/BuffIcons/心斋"),
            new("Buff延时攻", "Images/BuffIcons/延时攻"),
            new("Buff延时护甲", "Images/BuffIcons/延时护甲"),
            new("Buff滞气", "Images/BuffIcons/滞气"),
            new("Buff钟声", "Images/BuffIcons/钟声"),
            new("Buff灼烧", "Images/BuffIcons/灼烧"),
            
            // NodeIcons
            new("奇遇", "Images/NodeIcons/Adventure"),
            new("战斗", "Images/NodeIcons/Battle"),
            new("Boss", "Images/NodeIcons/Boss"),
            new("事件", "Images/NodeIcons/Event"),
            new("金钱", "Images/NodeIcons/JinQian"),
            new("人参", "Images/NodeIcons/RenShen"),
            new("人参果", "Images/NodeIcons/RenShenGuo"),
            new("商店", "Images/NodeIcons/Shop"),
            new("算卦", "Images/NodeIcons/SuanGua"),
            new("温泉", "Images/NodeIcons/WenQuan"),
            new("悟道", "Images/NodeIcons/WuDao"),
            new("修炼", "Images/NodeIcons/XiuLian"),
            new("以物易物", "Images/NodeIcons/YiWuYiWu"),
            
            // Characters
            new("CharacterTachie缺失立绘", "Images/Characters/缺失立绘"),
            new("徐福", "Images/Characters/01"),
            new("子非鱼", "Images/Characters/02"),
            new("子非燕", "Images/Characters/03"),
            new("风雨晴", "Images/Characters/04"),
            new("梦乃遥", "Images/Characters/05"),
            
            // Entities
            new("噬金甲", "Images/Monsters/01"),
            new("墨蛟", "Images/Monsters/02"),
            new("渊虾", "Images/Monsters/03"),
            new("九尾狐", "Images/Monsters/04"),
            new("推山兽", "Images/Monsters/05"),
            new("白泽", "Images/Monsters/06"),
            new("鲲", "Images/Monsters/07"),
            new("毕方", "Images/Monsters/08"),
            new("火蟾", "Images/Monsters/09"),
            new("麒麟", "Images/Monsters/10"),
            new("凌霄大圣", "Images/Monsters/鹿仙人"),
            new("龟仙人", "Images/Monsters/鹤仙人"),
            new("鹤仙人", "Images/Monsters/鹿仙人"),
            new("鹿仙人", "Images/Monsters/鹤仙人"),
            new("土行大圣", "Images/Monsters/鹿仙人"),

            // 卡牌
            new("Skill缺失插画",                              "Images/CardIllustrations/缺失插画"),
            new("Skill聚气术",                               "Images/CardIllustrations/聚气术"),
            new("Skill灵气匮乏",                               "Images/CardIllustrations/灵气匮乏"),
            new("Skill卡池已空",                               "Images/CardIllustrations/卡池已空"),
            // new("冲撞", "Images/Cards/冲撞"),
            new("Skill金刃",                                "Images/CardIllustrations/金刃"),
            new("Skill寻猎",                                "Images/CardIllustrations/寻猎"),
            new("Skill山风",                                "Images/CardIllustrations/山风"),
            new("Skill起势",                                "Images/CardIllustrations/起势"),
            new("Skill杀意",                                "Images/CardIllustrations/杀意"),
            new("Skill刺穴",                                "Images/CardIllustrations/刺穴"),
            new("Skill灵动",                                "Images/CardIllustrations/灵动"),
            new("Skill凛冽",                                "Images/CardIllustrations/凛冽"),
            new("Skill天地同寿",                              "Images/CardIllustrations/天地同寿"),
            new("Skill无妄",                                "Images/CardIllustrations/无妄"),
            new("Skill素弦",                                "Images/CardIllustrations/素弦"),
            new("Skill袖里乾坤",                              "Images/CardIllustrations/袖里乾坤"),
            new("Skill凝水",                                "Images/CardIllustrations/凝水"),
            new("Skill一莲托生",                              "Images/CardIllustrations/一莲托生"),
            new("Skill敛息",                                "Images/CardIllustrations/敛息"),
            new("Skill停云",                                "Images/CardIllustrations/停云"),
            new("Skill弹指",                                "Images/CardIllustrations/弹指"),
            new("Skill恋花",                                "Images/CardIllustrations/恋花"),
            new("Skill流霰",                                "Images/CardIllustrations/流霰"),
            new("Skill吐纳",                                "Images/CardIllustrations/吐纳"),
            new("Skill止水",                                "Images/CardIllustrations/止水"),
            new("Skill空幻",                                "Images/CardIllustrations/空幻"),
            new("Skill踏浪",                                "Images/CardIllustrations/踏浪"),
            new("Skill写意",                                "Images/CardIllustrations/写意"),
            new("Skill瑞雪",                                "Images/CardIllustrations/瑞雪"),
            new("Skill无念无想",                              "Images/CardIllustrations/无念无想"),
            new("Skill大鱼",                                "Images/CardIllustrations/大鱼"),
            new("Skill苦寒",                                "Images/CardIllustrations/苦寒"),
            new("Skill奔腾",                                "Images/CardIllustrations/奔腾"),
            new("Skill气吞山河",                              "Images/CardIllustrations/气吞山河"),
            new("Skill一梦如是",                              "Images/CardIllustrations/一梦如是"),
            new("Skill吞天",                                "Images/CardIllustrations/吞天"),
            new("Skill飞鸿踏雪",                              "Images/CardIllustrations/飞鸿踏雪"),
            new("Skill镜花水月",                              "Images/CardIllustrations/镜花水月"),
            new("Skill小松",                                "Images/CardIllustrations/小松"),
            new("Skill潜龙在渊",                              "Images/CardIllustrations/潜龙在渊"),
            new("Skill明神",                                "Images/CardIllustrations/明神"),
            new("Skill水滴石穿",                              "Images/CardIllustrations/水滴石穿"),
            new("Skill见龙在田",                              "Images/CardIllustrations/见龙在田"),
            new("Skill回春",                                "Images/CardIllustrations/回春"),
            new("Skill若竹",                                "Images/CardIllustrations/若竹"),
            new("Skill入木三分",                              "Images/CardIllustrations/入木三分"),
            new("Skill飞龙在天",                              "Images/CardIllustrations/飞龙在天"),
            new("Skill彼岸花",                                "Images/CardIllustrations/彼岸花"),
            new("Skill钟声",                                "Images/CardIllustrations/钟声"),
            new("Skill弱昙",                                "Images/CardIllustrations/弱昙"),
            new("Skill鹤回翔",                               "Images/CardIllustrations/鹤回翔"),
            new("Skill落英",                                "Images/CardIllustrations/落英"),
            new("Skill回响",                                "Images/CardIllustrations/回响"),
            new("Skill一叶知秋",                              "Images/CardIllustrations/一叶知秋"),
            new("Skill亢龙有悔",                              "Images/CardIllustrations/亢龙有悔"),
            new("Skill刹那芳华",                              "Images/CardIllustrations/刹那芳华"),
            new("Skill一念无量劫",                                 "Images/CardIllustrations/一念无量劫"),
            new("Skill云袖",                                "Images/CardIllustrations/云袖"),
            new("Skill轰天",                                "Images/CardIllustrations/轰天"),
            new("Skill正念",                                "Images/CardIllustrations/正念"),
            new("Skill拂晓",                                "Images/CardIllustrations/拂晓"),
            new("Skill九射",                                "Images/CardIllustrations/九射"),
            new("Skill不动明王诀",                                 "Images/CardIllustrations/不动明王诀"),
            new("Skill浴火",                                "Images/CardIllustrations/浴火"),
            new("Skill舍生",                                "Images/CardIllustrations/舍生"),
            new("Skill天衣无缝",                              "Images/CardIllustrations/天衣无缝"),
            new("Skill登宝塔",                               "Images/CardIllustrations/登宝塔"),
            new("Skill燎原",                                "Images/CardIllustrations/燎原"),
            new("Skill坐忘",                                "Images/CardIllustrations/坐忘"),
            new("Skill剑王行",                               "Images/CardIllustrations/剑王行"),
            new("Skill狂焰",                                "Images/CardIllustrations/狂焰"),
            new("Skill观众生",                               "Images/CardIllustrations/观众生"),
            new("Skill晚霞",                                "Images/CardIllustrations/晚霞"),
            new("Skill一舞惊鸿",                              "Images/CardIllustrations/一舞惊鸿"),
            new("Skill净天地",                               "Images/CardIllustrations/净天地"),
            new("Skill窑土",                                "Images/CardIllustrations/窑土"),
            new("Skill寸劲",                                "Images/CardIllustrations/寸劲"),
            new("Skill八极拳",                               "Images/CardIllustrations/八极拳"),
            new("Skill满招损",                               "Images/CardIllustrations/满招损"),
            new("Skill流沙",                                "Images/CardIllustrations/流沙"),
            new("Skill一力降十会",                                 "Images/CardIllustrations/一力降十会"),
            new("Skill边腿",                                "Images/CardIllustrations/边腿"),
            new("Skill连环腿",                               "Images/CardIllustrations/连环腿"),
            new("Skill崩山掌",                               "Images/CardIllustrations/崩山掌"),
            new("Skill玉骨",                                "Images/CardIllustrations/玉骨"),
            new("Skill箭疾步",                               "Images/CardIllustrations/箭疾步"),
            new("Skill震脚",                                "Images/CardIllustrations/震脚"),
            new("Skill孤山",                                "Images/CardIllustrations/孤山"),
            new("Skill龟息",                                "Images/CardIllustrations/龟息"),
            new("Skill冰肌",                                "Images/CardIllustrations/冰肌"),
            new("Skill一诺五岳",                              "Images/CardIllustrations/一诺五岳"),
            
            new("Skill正域彼四方",                              "Images/Cards/正域彼四方"),
            new("Skill射落金乌",                              "Images/Cards/射落金乌"),
            
            // 合成
            new("无法合成", "Images/MergeIllustrations/Invalid"),
            new("可以合成", "Images/MergeIllustrations/Valid"),
            new("金合成", "Images/MergeIllustrations/Jin"),
            new("水合成", "Images/MergeIllustrations/Shui"),
            new("木合成", "Images/MergeIllustrations/Mu"),
            new("火合成", "Images/MergeIllustrations/Huo"),
            new("土合成", "Images/MergeIllustrations/Tu"),
            
            // 背景
            new("练气背景", "Images/StageBackgrounds/01"),
            new("筑基背景", "Images/StageBackgrounds/02"),
            new("金丹背景", "Images/StageBackgrounds/03"),
            new("元婴背景", "Images/StageBackgrounds/04"),
            new("化神背景", "Images/StageBackgrounds/05"),
            
            // 阵法
            new("未激活阵法背景", "Images/Formation/Backgrounds/Inactive"),
            new("练气阵法背景", "Images/Formation/Backgrounds/LianQi"),
            new("筑基阵法背景", "Images/Formation/Backgrounds/ZhuJi"),
            new("金丹阵法背景", "Images/Formation/Backgrounds/JinDan"),
            new("元婴阵法背景", "Images/Formation/Backgrounds/YuanYing"),
            new("化神阵法背景", "Images/Formation/Backgrounds/HuaShen"),
            
            new("普通阵法发光", "Images/Formation/Glow/Normal"),
            new("接近激活阵法发光", "Images/Formation/Glow/NearExcited"),
            
            new("金灵阵", "Images/Formation/Icons/金灵阵"),
            new("水灵阵", "Images/Formation/Icons/水灵阵"),
            new("木灵阵", "Images/Formation/Icons/木灵阵"),
            new("火灵阵", "Images/Formation/Icons/火灵阵"),
            new("土灵阵", "Images/Formation/Icons/土灵阵"),
            new("攻击阵", "Images/Formation/Icons/攻击阵"),
            new("防御阵", "Images/Formation/Icons/防御阵"),
            new("灵气阵", "Images/Formation/Icons/灵气阵"),
            new("气血阵", "Images/Formation/Icons/气血阵"),
            new("燃命阵", "Images/Formation/Icons/燃命阵"),
            
            // RoomIcons
            new("AdventureRoomIcon", "Images/RoomIcons/AdventureRoomIcon"),
            new("AscensionRoomIcon", "Images/RoomIcons/AscensionRoomIcon"),
            new("BossRoomIcon", "Images/RoomIcons/BossRoomIcon"),
            new("EliteRoomIcon", "Images/RoomIcons/EliteRoomIcon"),
            new("UnderlingRoomIcon", "Images/RoomIcons/UnderlingRoomIcon"),
            new("RestRoomIcon", "Images/RoomIcons/RestRoomIcon"),
            new("ShopRoomIcon", "Images/RoomIcons/ShopRoomIcon"),
            new("EncounterRoomIcon", "Images/RoomIcons/EncounterRoomIcon"),
            
            // ShopIllustrations
            new("以物易物", "Images/ShopIllustrations/以物易物"),
            new("收藏家", "Images/ShopIllustrations/收藏家"),
            new("毕业季", "Images/ShopIllustrations/毕业季"),
            new("盲盒", "Images/ShopIllustrations/盲盒"),
            new("黑市", "Images/ShopIllustrations/黑市"),
            
            // FaceIcons
            new("Afraid", "Images/FaceIcons/Afraid"),
            new("Smirk", "Images/FaceIcons/Smirk"),
            
            // ArmorIcons
            new("ArmorIcon", "Images/ArmorIcons/ArmorIcon"),
            new("FragileIcon", "Images/ArmorIcons/FragileIcon"),
        });
    }

    public SpriteEntry MissingSkillIllustration() => this["Skill缺失插画"];
    public SpriteEntry ErrorBuffIcon() => this["Buff不存在"];
    public SpriteEntry MissingBuffIcon() => this["Buff缺失插画"];
    public SpriteEntry MissingCharacterTachie() => this["CharacterTachie缺失立绘"];
}
